version: "3.8"

volumes:
  postgres:
  pgadmin:

services:

  postgres:
    container_name: postgres
    image: postgres:13.1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - 5432:5432
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.29
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./docker_pgadmin_servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    ports:
      - 8889:80
    entrypoint:
      - /bin/sh
      - -c
      - /bin/echo 'postgres:5432:*:admin:password' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh
    restart: unless-stopped
